
### Base Url
# @baseUrl = https://fbcloneapi.onrender.com/api/v1
@baseUrl = http://localhost:8000/api/v1

### 1. Sign Up => signup
POST {{baseUrl}}/auth/sign_up
Accept: application/json
Content-Type: application/json

{
    "phone": "0358446198",
    "username": "daoluong",
    "password": "1234567@",
    "passwordConfirmation":"1234567@",
    "countryCode": "+84"
}

### 2. Login => login
# @name login
PATCH  {{baseUrl}}/auth/sign_in
Accept: application/json
Content-Type: application/json

{
    "phone": "0358446198",
    "password": "1234567@",
    "deviceId": "1242#CDSA"
}

### Auth Token
@authToken = {{login.response.body.$.data.accessToken}}

### 3. Logout => logout
PATCH  {{baseUrl}}/auth/sign_out
Accept: application/json
Authorization: Bearer {{authToken}}

### 4. Get user info => get_user_info
GET {{baseUrl}}/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### Get user profile
@userId = 63e60d2193d45a34d1067546
GET {{baseUrl}}/user/{{userId}}/profile
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 5. Update user profile => set_user_info
PUT {{baseUrl}}/user
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}
    # "cover_image": "dcdc"

{
    "phone": "0358446198",
    "username": "daovanluong124",
    "firstName": "dao",
    "lastName": "luong",
    "gender": "male",
    "date_of_birth": "12-10-2001",
    "description":"dcdcdc",
    "address": "hai ba trung",
    "city": "Ha Noi"
    # "country": "Viet Nam"
    # "avatar": "cdcdc",
}


### 6. Add post => add_post
POST {{baseUrl}}/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "images": ["https://images.unsplash.com/photo-1675789652767-d3bc9f56abd7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwyOHx8fGVufDB8fHx8&auto=format&fit=crop&w=2000&q=60","https://images.unsplash.com/photo-1675789652972-ee2040d2cc9a?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxlZGl0b3JpYWwtZmVlZHwxNTJ8fHxlbnwwfHx8fA%3D%3D&auto=format&fit=crop&w=2000&q=60"],
    "describe": "This is my post Luong Dao",
    "status": "hạnh phúc"
}

### 7. Edit post => edit_post


### 8. Delete post => delete_post


### 9. Get newfeed, get user posts => get_list_posts
### User's posts
GET {{baseUrl}}/post/user/63e60d4393d45a34d106754c
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### New feed
GET {{baseUrl}}/newfeeds/new
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

### 10. Like, unlike post => like_post
POST  {{baseUrl}}/post_reaction
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "postId": "63e7a2293338c9b972bdefde",
    "reactType": "like"
}

### 11. Get post comments => get_comment


### 11. Comment on a post => set_comment


### 12. Get user friends => get_user_friends


### 13. Request friend


### 14. Accept Friend


### 15. Get list requested friends


### 16. Change user password
PATCH {{baseUrl}}/user/change_password
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "oldPassword": "1234567@",
    "newPassword": "1234567@",
    "passwordConfirmation": "1234567@"
}

### 17. Block friends


### 18. Get list blocked friends


### 22. Get list suggested friends


### 19. Get list conversations


### 20. Get conversation


### 21. Delete conversation


### 23. Set read message


### 24. Send message


### 25. Delete message
